# arquivo docker compose para subir a demo da loja EBAC
# para subir a aplicação execute `docker-compose up -d`
# para subir a aplicação execute `docker-compose down`

version: "3.9"

services:
  wp_db:
    image: ernestobarbosa/lojaebacdb

  wp:
    depends_on:
      - wp_db
    image: ernestobarbosa/lojaebac
    ports:
      - "80:80"